# Support setting a device serial number when provisioning media. The escaped
# variable is resolved by fwup at burn time, so the serial number is not stored
# in the firmware archive.
uboot_setenv(uboot-env, "nerves_serial_number", "\${NERVES_SERIAL_NUMBER}")
